### PR TITLE
Fix attributes SAML Request for backwards compatib

### PR DESCRIPTION
**Pull request by giovapanasiti**
Fix attributes SAML Request for backwards compatibility

### CODE REVIEW

**Comment by random42** [comment]
What's the reason for not using the default signing of @node-saml? What backward compatibility are you targeting?

**Comment by giovapanasiti** [comment]
Poste Italiane wasn't working using your version and together with Poste IT people we came out with this fix

**Comment by giovapanasiti** [comment]
Rioslte le richieste della ultima review

**Comment by random42** [comment]
Grazie, pubblicata 2.0.3

**Pull request merged**
